VERSION 0.6
FROM bash:4.4
WORKDIR /setup-arena


bunjs-server:
	# We need an nginx container which can pass requests to our nodejs container,
	# as well as serve any static content.
	FROM oven/bun:1.0.5-alpine

	ARG version='0.1'
	ARG docker_registry='drayfocus/earthly-sample'
	ARG service='sample'

	RUN apk add --no-cache curl bash

	# Create app directory
	WORKDIR /usr/src/app

	## Then copy our app source code into the image
	COPY  ./app .

	# Install bun packages
	RUN bun install

	EXPOSE 8080
	CMD [ "bun", "run", "index.ts" ]

	# We need to add our NGINX template to the container for startup,
	# and configuration.
	COPY ./conf/nginx.conf /etc/nginx/templates/default.conf.template

	SAVE IMAGE --push ${docker_registry}/${service}_web_server:v${version}


websocket:
    FROM oven/bun:1.0.5-alpine

	ARG version='0.1'
	ARG docker_registry='drayfocus/earthly-sample'
	ARG service='sample'

	RUN apk add --no-cache curl bash

	# Create app directory
	WORKDIR /usr/src/app

	## Then copy our app source code into the image
	COPY  ./app .

	# Install bun packages
	RUN bun install

	EXPOSE 6001
	CMD [ "bun", "run", "index.ts" ]

	# We need to add our NGINX template to the container for startup,
	# and configuration.
	COPY ./conf/nginx.conf /etc/nginx/templates/default.conf.template

	SAVE IMAGE --push ${docker_registry}/${service}_websocket_server:v${version}
