VERSION 0.6

BUNJSAPP:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dir="./$service/environments/$env"
    ARG file="$dir/app-template.yaml"
	ARG version=0.1
	ARG httpsDomain1=''
	ARG CRD_KIND='CustomAppTemplate'
	ARG CRD_GROUP='app.resourcegroup.io'
	ARG OUTPUT="apiVersion: ${CRD_GROUP}/v1
kind: ${CRD_KIND}
metadata:
  name: ${service}
spec:
  serviceName: '${service}'
  environment: '${env}'
  deploymentReplicas: 1
  imageVersion: '${version}'
  letEncryptEmail: 'ray@greep.io'
  configsToUse: 'node-with-config'
"
	RUN mkdir -p $dir
    RUN echo "$OUTPUT" > "$file"


CONFIGMAP:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dirExtra="./$service/environments/$env/extras-$service"
    ARG YELLOW_CARD_BASE_URL=''
    ARG file="$dirExtra/configmap.yaml"
	ARG OUTPUT="apiVersion: v1
kind: ConfigMap
metadata:
  name: ${service}
  namespace: ${env}-${service}
data:
  YELLOW_CARD_BASE_URL: '{$YELLOW_CARD_BASE_URL}'
"
	RUN mkdir -p $dirExtra
  RUN echo "$OUTPUT" > "$file"

SECRETS:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dirExtra="./$service/environments/$env/extras-$service"
    ARG DB_USER='user'
    ARG DB_PASSWORD='password'
    ARG DB_HOST='localhost'
    ARG YELLOW_CARD_SECRET_KEY='secret_key'
    ARG YELLOW_CARD_API_KEY='api_key'
    ARG file="$dirExtra/secrets.yaml"
	ARG OUTPUT="apiVersion: v1
kind: Secret
metadata:
  name: ${service}
  namespace: ${env}-${service}
type: Opaque
stringData:
    DB_USERNAME: '$DB_USER'
    DB_PASSWORD: '$DB_PASSWORD'
    DB_DATABASE: '$service-${env}'
    DB_HOST: '$DB_HOST'
    DB_USE_SSL: 'true'
    YELLOW_CARD_SECRET_KEY: '${YELLOW_CARD_SECRET_KEY}'
    YELLOW_CARD_API_KEY: '${YELLOW_CARD_API_KEY}'
"
	RUN mkdir -p $dirExtra
  RUN echo "$OUTPUT" > "$file"
